### ISSUE TITLE
Create jade branch

### ISSUE THREAD

**Issue by progtologist** [kth-ros-pkg/force_torque_tools#11]
I have made some minor changes regarding eigen compatibility with Jade, please create a jade branch so I can issue a pull request.

Thx ;-)

**Comment by 130s** [comment]
Correct me if I'm wrong; there's a [migration notice about Eigen in Jade](http://wiki.ros.org/jade/Migration#Eigen_CMake_Module_in_cmake_modules) where you still can keep using the same code for Jade and prior distros. 
So if the change you have is about this cmake, my opinion is to try the solution in the link above to use the same code.

Branching works as a clean solution for the difference between distros, but it can inject disorder unless the repo is maintained consistently (don't get me wrong, I don't mean at all this repo is not maintained. It's just I've seen several repos that fell into a bad loop). 
2cents from me.

**Comment by progtologist** [comment]
I think that the "If you want to support both" part of the sentence refers to jade and k-turtle, but not indigo. I have also changed the preprocessor include paths to be <Eigen/...> (which should be the correct path if the Eigen headers are correctly found using cmake variables) and not <eigen3/Eigen/...>

**Comment by 130s** [comment]
> I have also changed the preprocessor include paths to be (which should be the correct path if the Eigen headers are correctly found using cmake variables) and not 

I'm not cmake-eigen guru but sounds like this is a good reason to create branch for jade.
So +1
I don't have a right to do so. Maybe @fevb 

Below is just a comment.

> I think that the "If you want to support both" part of the sentence refers to jade and k-turtle, but not indigo. 

My impression from the wiki statement was that for the situation described in wiki, we don't need to do anything for Jade.

**Comment by fevb** [comment]
Hi, sure I'll create a jade branch, sounds reasonable
