### ISSUE TITLE
Release plan into ROS Indigo, Jade?

### ISSUE THREAD

**Issue by 130s** [kth-ros-pkg/force_torque_tools#5]
Thank you for the nice toolset!
I like to utilize this package on ROS Indigo in particular. Any plan to do so?

**Comment by fevb** [comment]
Hi,

Good to know it is useful to others!

At the moment I'm kind of busy and won't be able to upgrade to Indigo for a while... however force_torque_tools only depends on fairly basic libraries (eigen, KDL) and moveit. 

It might work straight out of the box in Indigo, but I'm not entirely sure. Have you tried compiling it in Indigo?

**Comment by 130s** [comment]
From my experience I suggest you also change the default branch to the latest distro name so that by default pull requests go there.

**Comment by fevb** [comment]
Done! Thanks for the tip

**Comment by 130s** [comment]
Just a friendly reminder that it's not yet released into Indigo. The release will be completed by opening a pull request against rosdistro (just as you did for Hydro https://github.com/ros/rosdistro/pull/4874).

**Comment by fevb** [comment]
Hi,

Thanks for the reminder, I actually made a pull request just a few hours ago for indexing force_torque_tools into indigo: https://github.com/ros/rosdistro/pull/8188

Cheers

**Comment by 130s** [comment]
Sorry for not being clear!
https://github.com/ros/rosdistro/pull/8188 looks like only document index. I've been talking about binary release, which requires `release` entry (e.g. [this](https://github.com/ros/rosdistro/blob/1557f1038c42c25ce2ce0fa8ee3eaf302c1d0979/hydro/distribution.yaml#L4916)). I thought you did it for Hydro but it turned out you actually haven't.
You can follow http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease for doing that. In a nutshell, you use a tool called `bloom`.

If you're having troubles, I can help you do that. To do so, I need a write access to this repository though.

**Comment by fevb** [comment]
Oh ok I understand now, 

I'm a bit short on time these days but sure, I'll give you write access to the repo so that you can do the binary release

Thanks again!

**Comment by 130s** [comment]
Thx! I'll work on this in a few days.

**Comment by 130s** [comment]
Can someone who has a write access on this repository create a `git tag` maybe by following? 

```
$ cd %TOPDIR_force_torque_tools%
$ ls
force_torque_sensor_calib  force_torque_tools  gravity_compensation  LICENSE  README.md
$ catkin_prepare_release
```

This is necessary for making a ROS release. Looks like I don't have a write privilege to this repo, which is ok :).

**Comment by fevb** [comment]
Check your  inbox, I sent you an invitation a couple of weeks back for granting you write access... did you receive it? Here it says the invitation is still pending

**Comment by 130s** [comment]
Ah, found it! And I made a release request to Indigo. https://github.com/ros/rosdistro/pull/8472
Thanks a lot!

**Comment by fevb** [comment]
Thank you for the effort, really appreciate it!
